# Generated by Django 5.1.5 on 2025-02-15 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_selector', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='is_sub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='field',
            name='sub_form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='player_selector.field'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='is_sub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='sub_form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='player_selector.place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='time',
            name='is_sub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='time',
            name='sub_form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='player_selector.time'),
            preserve_default=False,
        ),
    ]
