# Generated by Django 5.1.5 on 2025-02-16 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_selector', '0004_field_is_sub_field_sub_form_place_is_sub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='sub_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player_selector.field'),
        ),
        migrations.AlterField(
            model_name='place',
            name='sub_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player_selector.place'),
        ),
        migrations.AlterField(
            model_name='time',
            name='sub_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player_selector.time'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
