# Generated by Django 5.1.5 on 2025-02-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_selector', '0005_alter_field_sub_form_alter_place_sub_form_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='besthomo',
            name='field',
        ),
        migrations.RemoveField(
            model_name='besthomo',
            name='place',
        ),
        migrations.RemoveField(
            model_name='besthomo',
            name='time',
        ),
        migrations.AddField(
            model_name='besthomo',
            name='field',
            field=models.ManyToManyField(to='player_selector.field'),
        ),
        migrations.AddField(
            model_name='besthomo',
            name='place',
            field=models.ManyToManyField(to='player_selector.place'),
        ),
        migrations.AddField(
            model_name='besthomo',
            name='time',
            field=models.ManyToManyField(to='player_selector.time'),
        ),
    ]
