# Generated by Django 5.1.5 on 2025-02-17 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_selector', '0006_remove_besthomo_field_remove_besthomo_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='is_sub',
        ),
        migrations.RemoveField(
            model_name='field',
            name='sub_form',
        ),
        migrations.RemoveField(
            model_name='place',
            name='is_sub',
        ),
        migrations.RemoveField(
            model_name='place',
            name='sub_form',
        ),
        migrations.RemoveField(
            model_name='time',
            name='is_sub',
        ),
        migrations.RemoveField(
            model_name='time',
            name='sub_form',
        ),
        migrations.AddField(
            model_name='field',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_field', to='player_selector.field'),
        ),
        migrations.AddField(
            model_name='place',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_places', to='player_selector.place'),
        ),
        migrations.AddField(
            model_name='time',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_times', to='player_selector.time'),
        ),
    ]
