# Generated by Django 5.1.5 on 2025-02-22 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_selector', '0007_remove_field_is_sub_remove_field_sub_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='player_selector.field'),
        ),
        migrations.AlterField(
            model_name='place',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='player_selector.place'),
        ),
        migrations.AlterField(
            model_name='time',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='player_selector.time'),
        ),
    ]
