# Generated by Django 5.1.5 on 2025-02-05 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_author',
            new_name='is_player',
        ),
    ]
